'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
export default function Home(){
 const [posts,setPosts]=useState([]),[selected,setSelected]=useState(null),[comments,setComments]=useState([]),[compose,setCompose]=useState(false),[title,setTitle]=useState(''),[content,setContent]=useState(''),[files,setFiles]=useState([]),[reply,setReply]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const {data}=await supabase.from('posts').select('*').order('created_at',{ascending:false});setPosts(data||[])};
 useEffect(()=>{load()},[]);
 const open=async p=>{setSelected(p);const {data}=await supabase.from('comments').select('*').eq('post_id',p.id).order('created_at');setComments(data||[])};
 async function publish(){if(!title.trim()||!content.trim())return alert('标题和内容都写一下');setBusy(true);try{let urls=[];for(const f of files.slice(0,4)){const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('post-images').upload(path,f,{contentType:f.type||undefined});if(error)throw error;const {data}=supabase.storage.from('post-images').getPublicUrl(path);urls.push(data.publicUrl)}const {error}=await supabase.from('posts').insert({title:title.trim(),content:content.trim(),images:urls});if(error)throw error;setTitle('');setContent('');setFiles([]);setCompose(false);await load()}catch(e){alert('发布失败：'+e.message)}finally{setBusy(false)}}
 async function sendReply(){if(!reply.trim())return;const {error}=await supabase.from('comments').insert({post_id:selected.id,content:reply.trim()});if(error)return alert('回复失败：'+error.message);setReply('');open(selected)}
 const ago=s=>{const m=Math.floor((Date.now()-new Date(s))/60000);return m<1?'刚刚':m<60?`${m}分钟前`:m<1440?`${Math.floor(m/60)}小时前`:`${Math.floor(m/1440)}天前`};
 if(selected)return <main className="shell"><header><b>匿名的熟人论坛</b></header><button className="back" onClick={()=>setSelected(null)}>← 返回帖子列表</button><article className="detail"><h1>{selected.title}</h1><small>匿名 · {ago(selected.created_at)}</small><p>{selected.content}</p>{(selected.images||[]).map(x=><img className="big" key={x} src={x}/>)}</article><h3 className="replytitle">回复</h3>{comments.length?comments.map((c,i)=><div className="comment" key={c.id}><small>{i+1}楼 · 匿名</small><div>{c.content}</div></div>):<div className="comment muted">还没人回复，你来坐一楼。</div>}<div className="reply"><input value={reply} onChange={e=>setReply(e.target.value)} placeholder="匿名回复一句..."/><button onClick={sendReply}>回复</button></div></main>;
 return <main className="shell"><header><div><b>匿名的熟人论坛</b><small>匿名 · 简单 · 略熟的大家</small></div><button onClick={()=>setCompose(true)}>发帖</button></header><nav>最新</nav><section>{posts.length?posts.map(p=><article className="post" key={p.id} onClick={()=>open(p)}><h2>{p.title}</h2><p>{p.content.length>90?p.content.slice(0,90)+'…':p.content}</p>{p.images?.length>0&&<div className="thumbs">{p.images.slice(0,3).map(x=><img key={x} src={x}/>)}</div>}<small>匿名 · {ago(p.created_at)}</small></article>):<div className="empty">还没有帖子。发第一帖吧。</div>}</section><button className="fab" onClick={()=>setCompose(true)}>＋</button>{compose&&<div className="overlay" onClick={e=>e.target===e.currentTarget&&setCompose(false)}><div className="sheet"><h2>发一个新帖子</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="标题"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="想说什么就说什么..."/><label className="upload">选择图片（最多4张）<input type="file" accept="image/*" multiple onChange={e=>setFiles([...e.target.files].slice(0,4))}/></label>{files.length>0&&<small>已选择 {files.length} 张图片</small>}<div className="actions"><button className="light" onClick={()=>setCompose(false)}>取消</button><button disabled={busy} onClick={publish}>{busy?'发布中...':'发布'}</button></div></div></div>}</main>
}
